import type { Metadata } from "next";
import { LegalPageShell } from "@/components/legal/legal-page-shell";

export const metadata: Metadata = {
  title: "Privacy Policy — BahayGo",
  description:
    "How BahayGo collects, uses, and protects personal data in line with the Philippine Data Privacy Act of 2012.",
};

export default function PrivacyPolicyPage() {
  return (
    <LegalPageShell title="Privacy Policy" current="privacy">
      <section className="space-y-4">
        <h2>Introduction</h2>
        <p>
          BahayGo (&quot;we,&quot; &quot;us,&quot; or &quot;our&quot;) operates an online real estate
          marketplace connecting buyers, renters, sellers, licensed real estate professionals, and
          brokerages in the Philippines. We are committed to protecting your personal data in
          accordance with the{" "}
          <strong>Data Privacy Act of 2012 (Republic Act No. 10173)</strong> and its implementing
          rules and regulations issued by the National Privacy Commission (NPC).
        </p>
        <p>
          This Privacy Policy explains what information we collect, how we use it, who we share it
          with, how long we keep it, and the rights you have as a data subject. By using BahayGo,
          you acknowledge that you have read this policy.
        </p>
      </section>

      <section className="space-y-4">
        <h2>Personal information we collect</h2>
        <p>Depending on how you use BahayGo, we may process:</p>
        <ul>
          <li>
            <strong>Account and identity data:</strong> name, email address, phone number, password
            (stored in hashed form), profile photo or avatar URL, and role (e.g., client, agent,
            broker, administrator).
          </li>
          <li>
            <strong>Property and listing data:</strong> addresses, descriptions, photos, pricing,
            availability, and related metadata you submit when listing or inquiring about
            properties.
          </li>
          <li>
            <strong>Professional verification:</strong> for agents and brokers, we may collect and
            display information relevant to licensing and accreditation, such as Professional
            Regulation Commission (PRC) license numbers, expiry dates, and brokerage affiliation,
            subject to our verification processes.
          </li>
          <li>
            <strong>Communications and leads:</strong> messages, viewing requests, contact forms,
            and notifications sent through or generated by the platform.
          </li>
          <li>
            <strong>Technical and usage data:</strong> IP address, device and browser type, general
            location (e.g., region), log data, and cookies or similar technologies used to operate
            and secure the service.
          </li>
        </ul>
      </section>

      <section className="space-y-4">
        <h2>Legal bases and purposes of processing</h2>
        <p>
          We process personal data for purposes that are compatible with the Data Privacy Act,
          including where processing is necessary for the performance of a contract with you, for
          our legitimate interests (such as fraud prevention, analytics, and improving the
          platform), to comply with legal obligations, or with your consent where required (for
          example, certain marketing communications or non-essential cookies).
        </p>
        <p>Typical purposes include:</p>
        <ul>
          <li>Creating and maintaining your account and profile.</li>
          <li>Displaying listings, agent and broker profiles, and facilitating introductions.</li>
          <li>Delivering notifications, reminders, and customer support.</li>
          <li>Verifying professional credentials and reducing misrepresentation.</li>
          <li>Detecting abuse, enforcing our Terms of Service, and protecting users.</li>
          <li>Complying with court orders, regulatory requests, and applicable Philippine law.</li>
        </ul>
      </section>

      <section className="space-y-4">
        <h2>Sharing of personal data</h2>
        <p>
          We do not sell your personal data. We may share information with: (1) other users of the
          platform as needed to fulfill listings and inquiries (for example, sharing contact details
          when you express interest in a property); (2) service providers who host our
          infrastructure, send email or SMS, or provide analytics, under contracts that require
          appropriate safeguards; (3) professional advisers or authorities when required by law; and
          (4) successors in the event of a merger or acquisition, subject to this policy or
          equivalent protections.
        </p>
        <p>
          Where we use processors located outside the Philippines, we take steps to ensure that
          transfers comply with NPC guidance and applicable cross-border transfer requirements.
        </p>
      </section>

      <section className="space-y-4">
        <h2>Retention and security</h2>
        <p>
          We retain personal data only as long as necessary for the purposes described, including
          legal, tax, and regulatory retention periods. We implement technical and organizational
          measures—such as encryption in transit, access controls, and staff training—to protect
          personal data against unauthorized access, alteration, disclosure, or destruction.
        </p>
      </section>

      <section className="space-y-4">
        <h2>Document storage</h2>
        <p>
          Identity documents, PRC licenses, and financial documents are stored in private encrypted
          storage and are never publicly accessible. Access is controlled via secure time-limited URLs.
          Documents are retained only as long as the account is active.
        </p>
      </section>

      <section className="space-y-4">
        <h2>Your rights as a data subject</h2>
        <p>
          Under the Data Privacy Act, you may have the right to be informed, to access, to rectify,
          to erase or block, to object, to data portability (where applicable), to damages, and to
          file a complaint with the NPC. To exercise these rights in connection with BahayGo, contact
          us through the channels listed on our Contact page. We will respond within reasonable
          periods prescribed by law and may need to verify your identity before fulfilling certain
          requests.
        </p>
      </section>

      <section className="space-y-4">
        <h2>Cookies and similar technologies</h2>
        <p>
          We use cookies and similar tools to keep you signed in, remember preferences, understand
          how the site is used, and improve security. You can control cookies through your browser
          settings; disabling some cookies may limit certain features of BahayGo.
        </p>
      </section>

      <section className="space-y-4">
        <h2>Children</h2>
        <p>
          BahayGo is not directed at individuals under the age of majority in the Philippines. We do
          not knowingly collect personal data from children without parental consent where such
          consent is required.
        </p>
      </section>

      <section className="space-y-4">
        <h2>Changes to this policy</h2>
        <p>
          We may update this Privacy Policy from time to time. We will post the revised version on
          this page and adjust the &quot;Last updated&quot; date. Material changes may be communicated
          through the platform or by email where appropriate.
        </p>
      </section>

      <section className="space-y-4">
        <h2>Contact</h2>
        <p>
          For privacy-related questions, requests, or concerns, please reach out through our{" "}
          <a href="/contact" className="font-semibold text-[#2C2C2C] underline underline-offset-4">
            Contact
          </a>{" "}
          page. You may also contact the National Privacy Commission at{" "}
          <a
            href="https://privacy.gov.ph"
            className="font-semibold text-[#2C2C2C] underline underline-offset-4"
            target="_blank"
            rel="noopener noreferrer"
          >
            privacy.gov.ph
          </a>
          .
        </p>
      </section>
    </LegalPageShell>
  );
}
